// Code generated by MockGen. DO NOT EDIT.
// Source: user-repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	databaseentity "rap-c/app/entity/database-entity"
	payloadentity "rap-c/app/entity/payload-entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *databaseentity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// GetTotalUsersByRequest mocks base method.
func (m *MockUserRepository) GetTotalUsersByRequest(ctx context.Context, req *payloadentity.GetUserListRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalUsersByRequest", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalUsersByRequest indicates an expected call of GetTotalUsersByRequest.
func (mr *MockUserRepositoryMockRecorder) GetTotalUsersByRequest(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalUsersByRequest", reflect.TypeOf((*MockUserRepository)(nil).GetTotalUsersByRequest), ctx, req)
}

// GetUserByField mocks base method.
func (m *MockUserRepository) GetUserByField(ctx context.Context, fieldName string, fieldValue interface{}, notFoundStatus int) (*databaseentity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByField", ctx, fieldName, fieldValue, notFoundStatus)
	ret0, _ := ret[0].(*databaseentity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByField indicates an expected call of GetUserByField.
func (mr *MockUserRepositoryMockRecorder) GetUserByField(ctx, fieldName, fieldValue, notFoundStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByField", reflect.TypeOf((*MockUserRepository)(nil).GetUserByField), ctx, fieldName, fieldValue, notFoundStatus)
}

// GetUsersByRequest mocks base method.
func (m *MockUserRepository) GetUsersByRequest(ctx context.Context, req *payloadentity.GetUserListRequest) ([]*databaseentity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByRequest", ctx, req)
	ret0, _ := ret[0].([]*databaseentity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByRequest indicates an expected call of GetUsersByRequest.
func (mr *MockUserRepositoryMockRecorder) GetUsersByRequest(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByRequest", reflect.TypeOf((*MockUserRepository)(nil).GetUsersByRequest), ctx, req)
}

// MapUserUsername mocks base method.
func (m *MockUserRepository) MapUserUsername(ctx context.Context, userIDs interface{}) (map[int]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapUserUsername", ctx, userIDs)
	ret0, _ := ret[0].(map[int]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapUserUsername indicates an expected call of MapUserUsername.
func (mr *MockUserRepositoryMockRecorder) MapUserUsername(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapUserUsername", reflect.TypeOf((*MockUserRepository)(nil).MapUserUsername), ctx, userIDs)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, user *databaseentity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, user)
}
